# Generated by Django 4.2.1 on 2024-01-17 04:41

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HideDataModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.FileField(upload_to="static\\hidedata")),
                ("imagename", models.CharField(max_length=50, null=True)),
                ("ciphertext", models.TextField(null=True)),
                ("algorithm", models.CharField(max_length=100, null=True)),
            ],
            options={
                "db_table": "Hidedata",
            },
        ),
        migrations.CreateModel(
            name="RequestModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fileid", models.CharField(max_length=100, null=True)),
                ("useremail", models.EmailField(max_length=254, null=True)),
                ("filename", models.CharField(max_length=100, null=True)),
                ("cipher_text", models.TextField(null=True)),
                ("algorithm", models.CharField(max_length=50, null=True)),
                ("elapsedtime", models.CharField(max_length=150, null=True)),
                ("key", models.CharField(max_length=100, null=True)),
                (
                    "status",
                    models.CharField(default="pending", max_length=100, null=True),
                ),
                ("requestedemail", models.EmailField(max_length=254, null=True)),
            ],
            options={
                "db_table": "Requests",
            },
        ),
        migrations.CreateModel(
            name="TextEncryptionModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("useremail", models.EmailField(max_length=254, null=True)),
                ("filename", models.CharField(max_length=100, null=True)),
                ("cipher_text", models.TextField(null=True)),
                ("algorithm", models.CharField(max_length=50, null=True)),
                ("elapsedtime", models.CharField(max_length=150, null=True)),
                ("key", models.CharField(max_length=100, null=True)),
                (
                    "status",
                    models.CharField(default="pending", max_length=100, null=True),
                ),
            ],
            options={
                "db_table": "Encryption",
            },
        ),
    ]
